---
- name: Get facts
  hosts: all
  connection: local                       # code is run locally
  gather_facts: no                        # don't gather facts
  tasks:
    - name: get facts from device
      napalm_get_facts:                   # NAPALM plugin
        hostname: "{{ host }}"            # start of connection parameters
        username: "{{ user }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        optional_args:
          port: "{{ port }}"             # end of connection parameters
        filter: ['facts']                # which NAPALM getters to use
      register: napalm_facts             # store information here
    - name: Print gathered facts
      debug:
        msg: "{{ napalm_facts.ansible_facts|to_nice_json }}"
      tags: [print_action]
